### ISSUE TITLE
[BUG] <sagemaker service unknow >

### ISSUE THREAD

**Issue by drewkrrb** [nerdswords/yet-another-cloudwatch-exporter#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.52.0

### Config file

apiVersion: v1alpha1
discovery:
  jobs:
    - type: sagemaker-processing
      regions:
        - ap-southeast-1
      period: 60
      length: 300
      metrics:
        - name: CPUUtilization
          statistics: [Average]

### Current Behavior

Am trying to run the new sagemaker auto discovery. Upon running my container I got this error:
Service is not in known list!: sagemaker-processing","level":"error","msg":"Error running yace","time":"2023-06-27T08:29:30Z"}

Am already running the latest version of the image.

**Comment by cristiangreco** [comment]
@drewkrrb the support for Sagemaker was merged yesterday in `master` and it's not part of any release yet. Can you wait for the next release v0.53.0? Alternatively, can you build yourself an image with the latest changes?
