### ISSUE TITLE
[FEATURE] missing assets (rpm) for 0.55

### ISSUE THREAD

**Issue by fabioasdias** [nerdswords/yet-another-cloudwatch-exporter#1177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

A hopefully small ask: version 0.55 does have pre-built rpm assets available.

yes, the Makefile is right there, but that's not entirely feasible/easy in some contexts. One might have yum but no "allowed" go compiler for instance. Also, thanks for un-deprecating custom namespaces.

Apologies for the unusual request, it isn't done lightly. Appreciate all the work and features.

**Comment by cristiangreco** [comment]
Release is out, sorry for the delay.
