### ISSUE TITLE
[FEATURE] Missing all assets except the source code for version 0.55.0

### ISSUE THREAD

**Issue by Reli4ble** [nerdswords/yet-another-cloudwatch-exporter#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello, all assets are missing except the source code for version 0.55.0.  It would be nice if these were delivered later so that we can use the finished binaries directly.

**Comment by fabioasdias** [comment]
Duplicated  #1177

**Comment by cristiangreco** [comment]
Closing as duplicate
