### ISSUE TITLE
Next release schedule v0.56.0

### ISSUE THREAD

**Issue by asantoz** [nerdswords/yet-another-cloudwatch-exporter#1228]
Hey folks!

Any idea of the schedule for the next release `v0.56.0`, there is some important bugfi for MWAA auto discovering that I would like to use.

https://github.com/nerdswords/yet-another-cloudwatch-exporter/commit/93dcda5c961d07df596b6a30697e1df772668359

Thanks in advance

**Comment by mloiseleur** [comment]
Same here :).

I'm also interested in a release containing the bugfix of this [issue](https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/1029).

**Comment by asantoz** [comment]
Hi @thomaspeitz 
Can you give us a help here on this subject?

**Comment by fabioasdias** [comment]
@cristiangreco news? v0.55.1 would work for me :)
Otherwise I'd end up having to custom package it and that's a bunch of red tape I'm begging you to spare me. Please?

**Comment by cristiangreco** [comment]
Release is out, sorry for the delay.

**Comment by lostick** [comment]
with the new release it should be working now.
