### ISSUE TITLE
[QUESTION] Should `nilToZero` return 0 for missing metrics?

### ISSUE THREAD

**Issue by andygeorge** [nerdswords/yet-another-cloudwatch-exporter#1241]
I have reporting/monitoring around the `HTTPCode_ELB_5XX_Count` (sum) metric, which is [event-driven](https://repost.aws/knowledge-center/cloudwatch-alarm-insufficient-data-state):

> An example of an event-driven metric is the [HTTPCode_ELB_5XX_Count](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html#load-balancer-metrics-alb) metric for an Application Load Balancer. The Elastic Load Balancing (ELB) service sends data points to this metric when there is a 5XX response from an ELB. If there are no 5XX errors during a period, then the result is an empty period (rather thn a zero value).

Should `nilToZero: true` return a 0 value when that metric is missing from CloudWatch (which is most of the time)? I have _sometimes_ gotten 0 values, but only when CloudWatch itself seems to report 0:

![image](https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/10601857/d24af3df-2c32-496d-b6e9-c7fd4d0a9059)

Any ideas to always get this metric to report some value within Prometheus?

**Comment by kgeckhart** [comment]
Depending on your end goal perhaps, `--enable-feature always-return-info-metrics` is an option for you? Setting this flag will ensure you still have info metrics to cover all available load balancers. We have used this to help us drive our dashboards to work around the behavior you're seeing.

As far as the direct issue goes IMO this is working as expected. I think it's important that these metrics mirror exactly what is available in cloudwatch, no data in cloudwatch = no metric. The level of statefulness and complexity which comes with attempting to produce metrics when they fall out of a source system is not fun.

**Comment by andygeorge** [comment]
Awesome, did not know about that feature flag! Guessing that's exactly what we'd like. Thank you so much!
