### ISSUE TITLE
[BUG] EKS Pod Identity not working

### ISSUE THREAD

**Issue by lostick** [nerdswords/yet-another-cloudwatch-exporter#1243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

`0.55.0`

### Current Behavior

We'd like to leverage [EKS Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) in lieu of IRSA, but it's currently failing as github.com/aws/aws-sdk-go (v1/v2) needs to be updated.

```
level=error ts=2023-12-08T14:16:23.893358461Z caller=main.go:68 version=v0.55.0
msg="Error running yace" err="failed to construct aws sdk v2 client cache: failed to load default aws config: invalid endpoint host, \"169.254.170.23\", only loopback hosts are allowed"
```

To fix this issue we need to update:
* `aws-sdk-go` to [v1.47.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11)
* `aws-sdk-go-v2` to [release-2023-11-14](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-11-14)

It looks like the master branch already contains the updated SDKs so all we theoretically need is to [cut a new release](https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/1228).

**Comment by TreeKat71** [comment]
Is it solved? I also wanna know if I can use this tool with IRSAv2.

**Comment by lostick** [comment]
with the new release it should be working now.
