### ISSUE TITLE
[QUESTION] Can Yace be used to export logs from EKS?

### ISSUE THREAD

**Issue by ArchitKhanna** [nerdswords/yet-another-cloudwatch-exporter#1423]
EKS by default has Cloudwatch logging which can be enabled. However, I would like to bypass this and ship the logs directly to S3, is this possible?

Note: Looking to ship EKS control plane logs, not metrics.

**Comment by NickAdolf** [comment]
Short answer is no. YACE is in the game of getting metrics out of Cloudwatch so not really the right tool in this case.

**Comment by ArchitKhanna** [comment]
Yeah I reached that conclusion too after much deliberation. Thank you for the reply though!
