### ISSUE TITLE
Config file syntax error complaining about 'missing apiVersion'

### ISSUE THREAD

**Issue by danilomattoscamossi** [nerdswords/yet-another-cloudwatch-exporter#1455]
Hello,

I have deployed YACE into my Kubernetes Cluster, however it is complaining about 'missing apiVersion' in pod log.

**_{"caller":"config.go:534","err":"missing apiVersion","level":"warn","msg":"config file syntax error","ts":"2024-07-01T14:21:29.685150462Z","version":"v0.61.2"}
{"caller":"config.go:536","level":"warn","msg":"Config file error(s) detected: Yace might not work as expected. Future versions of Yace might fail to run with an invalid config file.","ts":"2024-07-01T14:21:29.685170549Z","version":"v0.61.2"}_**

My Config Map already have the apiVersion attribute as shown below:

_**apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-config
  namespace: yace
data:
  config.yml: |**_

As well the Deployment yaml file:

**_apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace
  namespace: yace_**

Can you help identify where it is missing the apiVersion attribute?

**Comment by cristiangreco** [comment]
Hi @danilomattoscamossi,

the yace config file needs and `apiVersion: v1alpha1` field, like in this example https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/examples/ec2.yml

Please doublecheck the configmap you pasted above:

```
apiVersion: v1
kind: ConfigMap
metadata:
name: yace-config
namespace: yace
data:
config.yml: |
```

what is the actual content of `config.yml`?

**Comment by danilomattoscamossi** [comment]
Hi @cristiangreco, thanks.

Yes, this is my current yace config.

Then I tried your suggestion and got this issue:

"no matches for kind "ConfigMap" in version "v1alpha1""

Below this is how my config looks like:

<img width="172" alt="yace_config" src="https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/4260344/4a7957f3-3946-4115-be35-2c9f2ff1f0da">

**Comment by cristiangreco** [comment]
The `apiVersion` field you changed belongs to the ConfigMap definition, so it's the wrong one. Overall it should look like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-config
  namespace: yace
data:
  config.yml: |
    apiVersion: v1alpha1
    discovery:
      ...
```

**Comment by danilomattoscamossi** [comment]
Thank you @cristiangreco, it worked.
