### ISSUE TITLE
Can't add dimension except for InstanceId in AWS/EC2

### ISSUE THREAD

**Issue by singhjagmohan1000** [nerdswords/yet-another-cloudwatch-exporter#241]
I want to add AutoScalingGroupName dimension in "AWS/EC2", but adding that dimension caused EC2 metrics' disappearing.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ec2-metricscollected.html

**Comment by cristiangreco** [comment]
Closing this as it seems to refer to a really old version of yace. If you can still reproduce the issue with the latest realease please feel free to reopen.
