### ISSUE TITLE
Feature request: Add Global Accelerator metrics

### ISSUE THREAD

**Issue by omernave1** [nerdswords/yet-another-cloudwatch-exporter#324]
Add global accelerator stats to yace

**Comment by thomaspeitz** [comment]
Hey @omernave1 ,

tried to work on this today and get it merged but I have no Idea I did not use a global accelerator yet.

Could you please show me some metrics via screenshot here or if you want it secure (keybase: https://keybase.io/tsupertramp)

Then I understand what you want to measure and can implement it correctly. Thanks!

**Comment by thomaspeitz** [comment]
No input. So not working on this currently.

**Comment by FlorianNeacsu** [comment]
@thomaspeitz I have deployed your changes from https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/522 and the ga metrics are scraped. When are you planning to release it?
<img width="341" alt="Screenshot 2022-03-08 at 10 29 52" src="https://user-images.githubusercontent.com/38534926/157218572-ec6ca007-26c8-44a0-b5aa-d21545e38a32.png">
d
