### ISSUE TITLE
Couldn't describe resources for region eu-central-1: WebIdentityErr: failed to retrieve credentials\ncaused by: ValidationError: Request ARN is invalid\n\tstatus code: 400, request id: e0d26f84-8359-4f86-b946-47afba3c17c7\n","time":"2021-03-24T09:54:40Z"}

### ISSUE THREAD

**Issue by chadiandianwenrou** [nerdswords/yet-another-cloudwatch-exporter#343]
Specify the policy ARN in the serviceaccount

error：
Couldn't describe resources for region eu-central-1: WebIdentityErr: failed to retrieve credentials\ncaused by: ValidationError: Request ARN is invalid\n\tstatus code: 400, request id: e0d26f84-8359-4f86-b946-47afba3c17c7\n","time":"2021-03-24T09:54:40Z"}

**Comment by cristiangreco** [comment]
Closing this as it seems to refer to a really old version of yace. If you can still reproduce the issue with the latest realease please feel free to reopen.
