### ISSUE TITLE
Fix on China AWS support

### ISSUE THREAD

**Issue by insectme** [nerdswords/yet-another-cloudwatch-exporter#344]
if run Yace on china AWS, there is error “Couldn't describe resources for region cn-northwest-1: InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403,” and china AWS is in seperate infra.

Session new need to specified region, we fixed code based on Release 0.26.3-alpha, it has been tested successfully in China. 

and in aws_cloudwatch.go ln50:

func createStsSession(roleArn string) 

this part of code seems new adding, and region is unnecessary here. It has been tested.

**Comment by thomaspeitz** [comment]
Was fixed and merged

**Comment by alibner** [comment]
the same issue ; `{"arn":"","error":"InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 46cbd89f-1a5d-49b4-996f-c2b616f4479c","job_type":"alb","level":"error","msg":"Couldn't get account Id","region":"cn-northwest-1","time":"2023-10-24T11:43:05Z"}.`
