### ISSUE TITLE
Feature request: Add live reload support for configuration files

### ISSUE THREAD

**Issue by Diggs27** [nerdswords/yet-another-cloudwatch-exporter#346]
Prometheus and other open source monitoring tools have a feature that allow you to hot reload configuration files. 
In the prometheus project, making a `POST` request to the  '/-/reload` endpoint will attempt to validate the config file and reload changes. This feature request is for the yace project to support a similar feature.

**Comment by antoniomerlin** [comment]
In this feature what will be the status of metrics scraping. Should it scrape on endpoint hit.

**Comment by cristiangreco** [comment]
This has been implemented.
