### ISSUE TITLE
0.27.0 : release missing?

### ISSUE THREAD

**Issue by BitProcessor** [nerdswords/yet-another-cloudwatch-exporter#376]
Noticed commit: https://github.com/ivx/yet-another-cloudwatch-exporter/commit/02f97ff5f589569189496e5023eebbbceda7bdf6

But no release in Github, no docker image?

**Comment by devstek** [comment]
Also looking for new version as i need mq metrics.

So i just build it by myself:
`docker build . yace_base:v0.27.0-alpha`

**Comment by thomaspeitz** [comment]
Sorry for not responding so long. New versions have everything.
