### ISSUE TITLE
ALB metrics are wrong

### ISSUE THREAD

**Issue by probert-mdf** [nerdswords/yet-another-cloudwatch-exporter#391]
Hello,

Using 0.25-alpha. I found out that the metrics for anything ALB/ELB are wrong. For example, when I do a load test, I see 75 MBps load in CloudWatch, which make sense since I do 10 000 requests, in batch of 100 concurrent requests. But in Prometheus, I see... 12 Mbps for aws_alb_processed_bytes_sum!

 If I use:

 aws cloudwatch get-metric-statistics --metric-name ProcessedBytes  --namespace AWS/ApplicationELB ,,,

The numbers are good. So it's really the metrics we get from YACE that are not accurate.

Our config was with a period of 60 and length of 600. I tried to use 600 as the period, no change.

This is only for ALB, for other metrics (EC2, RDS, ECS), the metrics are good.

**Comment by jrbenito** [comment]
Check the output of yace on the `/metrics` endpoint. See if number matches what you see in the aws cli.

**Comment by probert-mdf** [comment]
They don't match, but the difference is not big. And in /metrics, it's the same value for over 15 minutes, while the value change every minute when I call _aws cloudwatch get-metric-statistics --metric-name TargetResponseTime_ directly.

**Comment by jrbenito** [comment]
Please, verify `Decoupled scraping` in the README file.

By default, YACE will query AWS Cloudwatch ONCE every 300s (5 minutes) and keep displaying the same information over that period until it queries Cloudwatch again. So, manually querying AWS will update number while YACE will not.

What you are seeing in /metrics is a point in time, the SUM statistic in that point will be one, and if you query AWS 10s later it might be other. Same goes for AVG and others.

**Comment by probert-mdf** [comment]
We are not setting either 'decoupled-scraping' or 'scraping-interval'. so it should resolve to 300 seconds, but it looks more like 900 seconds (and I did use curl, just to make sure that it was not the browser cache who kept the previous values).

**Comment by cristiangreco** [comment]
Closing this as it seems to refer to a really old version of yace. If you can still reproduce the issue with the latest realease please feel free to reopen.
