### ISSUE TITLE
Regex to receive only value between slashes

### ISSUE THREAD

**Issue by chagainota** [nerdswords/yet-another-cloudwatch-exporter#428]
Hi

I would like to know if there an option when getting the fields dimension_LoadBalancer 
dimension_TargetGroup, to get only the name between slashes.
for example now I get:
net/chagain-test/f8cc3cbac228d90e
and I want only:
chagain-test

Thx

**Comment by thomaspeitz** [comment]
Hey @chagainota,

I think you could do this on your prometheus instance via relabeling
https://medium.com/quiq-blog/prometheus-relabeling-tricks-6ae62c56cbda

It is not intended to implement it in yace source code.

Greetings, Thomas
