### ISSUE TITLE
cloudwatch timestamp stuck after setting "addCloudwatchTimestamp: true"

### ISSUE THREAD

**Issue by EthanGao-oss** [nerdswords/yet-another-cloudwatch-exporter#453]
YACE image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.31.0-alpha
startup_args: - --config.file=/config/config_1m.cfg - --scraping-interval=60 - -debug
debug_logs: 
![image](https://user-images.githubusercontent.com/53399006/135023117-028e2b6d-c7e5-4f42-ab77-50c5a9790c04.png)

scraping_config_file:

> apiVersion: v1alpha1
> discovery:
>   exportedTagsOnMetrics:
>     alb:
>       - Environment
>     rds:
>       - Environment
>     ec:
>       - Environment
>     sqs:
>       - Environment
>   jobs:
>   - type: rds
>     regions:
>       - us-west-2
>     addCloudwatchTimestamp: true
>     period: 60
>     length: 120
>     metrics:
>       - name: CPUUtilization
>         statistics:
>         - Average
>       - name: Deadlocks
>         statistics:
>         - Average
>       - name: DatabaseConnections
>         statistics:
>         - Average
>       - name: FreeableMemory
>         statistics:
>         - Average_

**Comment by EthanGao-oss** [comment]
FYI. v0.30.1-alpha seems not having this issue.

**Comment by thomaspeitz** [comment]
Awesome
