### ISSUE TITLE
Unexpected series for EC2 metrics

### ISSUE THREAD

**Issue by kgeckhart** [nerdswords/yet-another-cloudwatch-exporter#468]
When using a discovery job to pull in CPU Utilization Maximum for EC2 instances it appears as though each available dimension creates a new series. 

Given 2 t2.micro instances in the eu-west-2 region I expected two series (plus or minus various dimensions which might or might not be available)
```
aws_ec2_cpuutilization_maximum{account_id="XXXXXXXXXXXX",dimension_ImageId="ami-aaa",dimension_InstanceId="i-ccc",dimension_InstanceType="t2.micro",name="arn:aws:ec2:eu-west-2:XXXXXXXXXXXX:instance/i-ccc",region="eu-west-2"} 0.169491525423731
aws_ec2_cpuutilization_maximum{account_id="XXXXXXXXXXXX",dimension_ImageId="ami-bbb",dimension_InstanceId="i-ddd",dimension_InstanceType="t2.micro",name="arn:aws:ec2:eu-west-2:XXXXXXXXXXXX:instance/i-ddd",region="eu-west-2"} 0.338983050847535
```

Instead I'm seeing 6,
```
aws_ec2_cpuutilization_maximum{account_id="XXXXXXXXXXXX",dimension_ImageId="",dimension_InstanceId="",dimension_InstanceType="",name="global",region="eu-west-2"} 0.338983050847535
aws_ec2_cpuutilization_maximum{account_id="XXXXXXXXXXXX",dimension_ImageId="",dimension_InstanceId="",dimension_InstanceType="t2.micro",name="global",region="eu-west-2"} 0.338983050847535
aws_ec2_cpuutilization_maximum{account_id="XXXXXXXXXXXX",dimension_ImageId="",dimension_InstanceId="i-ccc",dimension_InstanceType="",name="arn:aws:ec2:eu-west-2:XXXXXXXXXXXX:instance/i-ccc",region="eu-west-2"} 0.169491525423731
aws_ec2_cpuutilization_maximum{account_id="XXXXXXXXXXXX",dimension_ImageId="",dimension_InstanceId="i-ddd",dimension_InstanceType="",name="arn:aws:ec2:eu-west-2:XXXXXXXXXXXX:instance/i-ddd",region="eu-west-2"} 0.338983050847535
aws_ec2_cpuutilization_maximum{account_id="XXXXXXXXXXXX",dimension_ImageId="ami-aaa",dimension_InstanceId="",dimension_InstanceType="",name="global",region="eu-west-2"} 0.169491525423731
aws_ec2_cpuutilization_maximum{account_id="XXXXXXXXXXXX",dimension_ImageId="ami-bbb",dimension_InstanceId="",dimension_InstanceType="",name="global",region="eu-west-2"} 0.338983050847535
```
I find the series with a name of global a little confusing because their name implies a holistic measurement but the values appear to track a single instance. This structuring makes it hard to do visualizations across the various dimensions.

This appears to stem from the fact that the [AWS ListMetrics API](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudwatch/list-metrics.html#examples) doesn't group dimensions with the same Namespace + Metric in to the same result. Is it valuable to adjust how this works to roll up the dimensions on to a single series associated with the instance? Happy to take on the effort just wanted to validate it made sense first. This appears to apply to other series and metrics as well so it would have a large impact on the way data is currently returned.

**Comment by dfredell** [comment]
I think this is the same issue as in #404

**Comment by richie-tt** [comment]
I have the same issue for EC2, and wondering what I should put to `dimensionNameRequirements` options 

like it is in this example [#issuecomment-1247685098](https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/404#issuecomment-1247685098)

**Comment by kgeckhart** [comment]
Closing as this is expected behavior
