### ISSUE TITLE
ALB metrics not updating - using 0.31.0-alpha

### ISSUE THREAD

**Issue by benrurepo** [nerdswords/yet-another-cloudwatch-exporter#474]
I see there are few similar issues - SQS, cloudfront - maybe the same fix is needed also for ALB metrics

**Comment by nutslove** [comment]
I think it's not only about specific resources but all resources metrics are exported only once.
※In my case, Elascticache metrcis are also exported only once.

**Comment by aleslash** [comment]
I'm rolling back to the v0.29.0-alpha and the metrics of my apigateway got back on updating

**Comment by thomaspeitz** [comment]
Should be fixed with newest release

**Comment by aleslash** [comment]
the new version (v0.32) worked for me
Tks @thomaspeitz

**Comment by thomaspeitz** [comment]
Awesome to hear <3
