### ISSUE TITLE
No new data on any of the metrics

### ISSUE THREAD

**Issue by xushiba** [nerdswords/yet-another-cloudwatch-exporter#478]
Data is generated only at the moment of startup, and all subsequent data is the same as before, and logs are always logged at the start time

configs：

   - type: ec2
    length: 300
    regions:
      - ap-northeast-1
      - us-east-1
    metrics:
      - name: CPUCreditUsage
        statistics:
          - Average
        period: 60
        length: 600
      - name: CPUUtilization
        statistics:
          - Average
        period: 300

**Comment by bt909** [comment]
I experience the same issue and try to find my problem. I contrast to this I have set period and length all to 600.

**Comment by xushiba** [comment]
> I experience the same issue and try to find my problem. I contrast to this I have set period and length all to 600.

@bt909 
Does the data change after modification?
If the length and period are too long, real-time alarms will be affected

**Comment by bt909** [comment]
Hello @xushiba,

I just use the previous release right now with the same configuration and don't have this issue anymore. Would you like to just give 0.30.1-alpha a try?

**Comment by thomaspeitz** [comment]
Can you try the newest releasé?

**Comment by bt909** [comment]
Hey @thomaspeitz,

the newest release solves my issue. I have not opened this issue, so I just comment here, but thank you.

**Comment by thomaspeitz** [comment]
Closing this one <3
