### ISSUE TITLE
[FEATURE] Add helm chart

### ISSUE THREAD

**Issue by thomaspeitz** [nerdswords/yet-another-cloudwatch-exporter#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I made a big error during the project. Not adding one of the multiple helm chart prs to this repository as I did
see helm as only one of the k8s deployment methods.

For me helm is the defacto standard of deploying to kubernetes currently and thats the reason why I would like to get a
helm chart into this repository and release it together with the code.

I am using this project currently: https://github.com/mogaal/helm-charts

Lets chat with the contributor.

**Comment by QualoZe0t** [comment]
Hi, i have tried to deploy helm chart using by mogaal helm chart: https://mogaal.github.io/helm-charts/ but after deployment and using tag image v0.33.0 but I am getting unhealthy state on pod 

```
Events:
  Warning  Unhealthy  97s   kubelet            Readiness probe failed: Get "http://10.71.243.42:5000/": dial tcp 10.71.243.42:5000: i/o timeout (Client.Timeout exceeded while awaiting headers)
```

is anyone was able to make helm-chart working ?

**Comment by patrungel** [comment]
@QualoZe0t, `v0.33.0-alpha` works in my (EKS) environment and default settings for probes and ports.

**Comment by patrungel** [comment]
@thomaspeitz is there any progress about incorporating mogaal's chart? If there isn't I could start a new one in this repo.
