### ISSUE TITLE
[BUG] Config reload leaks goroutines

### ISSUE THREAD

**Issue by gumpt** [nerdswords/yet-another-cloudwatch-exporter#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the `/reload` endpoint is hit, a new goroutine for scraping is kicked off. The goroutine running the old scrape from the old configuration does not stop, resulting in multiple scrapes and scrapes running on undesired config.

### Expected Behavior

When the `/reload` endpoint is hit, the old goroutine is signalled to stop.

### Steps To Reproduce

1. With any config, run with `--scrape-interval 10`
2. In a separate terminal, run `for i in `seq 1 10`; do curl -X POST localhost:5000/reload; sleep 1; done`
3. Look at the logs in the first terminal to see that there are many goroutines running scrapes.	

### Anything else?

Happy to work on a patch to upstream if fixing is desired.

**Comment by thomaspeitz** [comment]
Wow that would be awesome! - Would be happy to merge it!

Sorry for the long delay was doing vacation!
