### ISSUE TITLE
[FEATURE] support appstream

### ISSUE THREAD

**Issue by jhuesemann** [nerdswords/yet-another-cloudwatch-exporter#500]
**Feature description**
We need an export for the appstream service.
I added it in services.go:

		{
			Namespace: "AWS/AppStream",
			Alias:     "appstream",
			ResourceFilters: []*string{
				aws.String("appstream"),
			},
			DimensionRegexps: []*string{
				aws.String(":fleet/(?P<FleetName>[^/]+)"),
			},
		},	

**What might the configuration look like?**

[yace-config-appstream.txt](https://github.com/nerdswords/yet-another-cloudwatch-exporter/files/7712711/yace-config-appstream.txt)

**Anything else?**
No response

**Comment by cristiangreco** [comment]
Support for appstream has been added.
