### ISSUE TITLE
[FEATURE] Support for RDS enhanced monitoring

### ISSUE THREAD

**Issue by yann-soubeyrand** [nerdswords/yet-another-cloudwatch-exporter#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello,

From what I see, RDS enhanced monitoring metrics aren’t supported by this exporter. I guess it’s normal since RDS enhanced monitoring isn’t baked by Cloudwatch metrics, but by Cloudwatch logs. My question is, could it be in the scope of this exporter to fetch RDS enhanced monitoring metrics? If yes, any advice on how this support should be added to this exporter (as a peculiarity of RDS service or in a more generic way, etc)?

### Anything else?

AWS doc on RDS enhanced monitoring: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.html.

**Comment by thomaspeitz** [comment]
Sorry Cloudwatch logs are not in the scope of the exporter currently. - Can't you make a cloudwatch metric out of the logs somehow and then use this custom metric?

**Comment by yann-soubeyrand** [comment]
Understandable ;-) Yes, a collegue of mine made the same suggestion, I’ll try to go this way, thanks!
