### ISSUE TITLE
Disable decoupled scraping

### ISSUE THREAD

**Issue by johnlane** [nerdswords/yet-another-cloudwatch-exporter#525]
I note that, with recent versions, the `--decoupled-scraping` option [no longer exists](https://github.com/nerdswords/yet-another-cloudwatch-exporter/commit/3a6e620c925f3c75d765a1787194c56d51f286c5) - it is always enabled. The message in the change log says that "Decoupled scraping is now default" - does this imply there is a non-default way to to "coupled scraping" (i.e. scraping for each http request made to the metrics endpoint, like earlier versions without using `--decoupled-scraping`) ?

**Comment by cristiangreco** [comment]
This feature has been removed. If you need better control over scraping you might embed yace as a library into your own application: https://github.com/nerdswords/yet-another-cloudwatch-exporter#embedding-yace-as-a-library-in-an-external-application
