### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by frankguo-dyedurham** [nerdswords/yet-another-cloudwatch-exporter#528]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I ran into some issues to run Yace locally using docker command in the document and they took me some time to solve.
1. Couldn't read /tmp/config.yml: open /tmp/config.yml: permission denied
2.  EnvAccessKeyNotFound: failed to find credentials in the environment

Solutions:
1. add the option --user "$(id -u):$(id -g)" in the docker run command
2. use the options in the docker run command instead of the bind mount of the credentials file
-e AWS_ACCESS_KEY_ID='' -e AWS_SECRET_ACCESS_KEY='' -e AWS_DEFAULT_REGION='' 

### Expected Behavior

Add these error cases and solutions in the docker run section in the document or may update the docker command if these are common cases.

### Anything else?

Accidentally labeled this as a Bug. It seems not able to be removed. Please help remove the bug label.

**Comment by cristiangreco** [comment]
Closing this as it seems to refer to a really old version of yace. If you can still reproduce the issue with the latest realease please feel free to reopen.
