### ISSUE TITLE
[FEATURE] ContainerInsights (EKS)

### ISSUE THREAD

**Issue by sweepkim** [nerdswords/yet-another-cloudwatch-exporter#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I would like to ask if EKS ContainerInsights can be supported in future.
The Namespace of this is ContainerInsights and It's different with ECS/Containerinsights.

### What might the configuration look like?

discovery:
   jobs:
   - type: eks-containerinsights
     period: 300
     length: 300
     metrics:
     - name: pod_cpu_utilization
        statistics: [Average]

### Anything else?

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-EKS.html

**Comment by cristiangreco** [comment]
This is supported now.
