### ISSUE TITLE
Confirm API Gateway v2 support

### ISSUE THREAD

**Issue by nabadger** [nerdswords/yet-another-cloudwatch-exporter#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

From what I can tell, this project currently only supports the REST API Gateway (v1).

Can this be confirmed? In terms of metrics `aws_apigateway_info` is only returning REST instances, although other related metrics do return HTTP gateway values for `dimension_ApiId`.

Looking at the code though, I don't see anything using https://github.com/aws/aws-sdk-go/tree/main/service/apigatewayv2

I would love support for HTTP and WebSocket metrics :)

### Anything else?

Related #426

**Comment by PerGon** [comment]
We are also quite interested in this feature. Today it's my last day before vacations, but in a month or so we could possibly help getting this one thru.

In the meantime, I'm keen in hearing from @thomaspeitz his thoughts on this.

One things we've noticed is that AWS released a new API ([apigateway v2](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigatewayv2/index.html) as opposed to the existing one [apigateway](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigateway/index.html)) (which @nabadger correctly mentioned in the OP) but in cloudwatch these two are both under the API name `AWS/ApiGateway`. Does this bring some complications when adding it to yace?

**Comment by quanlk2511** [comment]
Hi guys, do we have any progress on this enhancement?
I'm currently facing issue with http apigw metrics discovery, dimensions auto-discovery doesn't seem to work with http gw.
I have tried adding dimensionNameRequirements already (ApiId, Resource, Method, Stage), but got "msg":"No metrics data found".

Looking forward to any update on this.
BR,
Quan

**Comment by matej-g** [comment]
Hey folks 👋,
I just hit the same issue today, I decided to add support for API Gateway V2, feel free to check out the PR: https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/857

**Comment by bogdankatishev** [comment]
We also need this :)
