### ISSUE TITLE
[FEATURE] New Repo Owners/Maintainers 

### ISSUE THREAD

**Issue by datsabk** [nerdswords/yet-another-cloudwatch-exporter#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The repository is gaining traction but I see the repository owner is unable to look at PRs on regular basis. Wondering if we could add a few more trusted maintainers to speed up the process and take this to a stable release more quickly. 

We, at Twilio Segment, have started to utilize this utility and forked a branch into our organization. We would be happy to take up the ownership to quickly review some PRs and co-own the product development overall. 

YACE is a great product and interestingly there's no replacement for it at present - So looking for thumbsup on this and requesting quick attention from @thomaspeitz for the same.

**Comment by justinwyer** [comment]
We're also about to adopt this and would be willing to contribute.
