### ISSUE TITLE
Add support for AWS/MWAA metrics

### ISSUE THREAD

**Issue by kiaev** [nerdswords/yet-another-cloudwatch-exporter#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Autodiscovering AWS/MWAA not supported. 
https://docs.aws.amazon.com/mwaa/latest/userguide/accessing-metrics-cw-container-queue-db.html
this is about the AWS / MWAA service, do not confuse with Amazon / MWAA these are different services.
AmazonMWAA - supported
https://docs.aws.amazon.com/mwaa/latest/userguide/access-metrics-cw-202.html

**Comment by hugree** [comment]
Is there any update on this? 

Airflow internal metrics are supported now
<img width="1769" alt="image" src="https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/18511093/82e5993c-0f6b-41b6-93c5-7c5301fe8969">

But the resources utilization metrics
<img width="1341" alt="image" src="https://github.com/nerdswords/yet-another-cloudwatch-exporter/assets/18511093/e1a261b0-c496-49a4-9bba-1fda579ca283">
are not supported?

Can this be added?

**Comment by cristiangreco** [comment]
This is supported now.
