### ISSUE TITLE
dimension_DBInstanceIdentifier is not available anymore for RDS job

### ISSUE THREAD

**Issue by danilomattoscamossi** [nerdswords/yet-another-cloudwatch-exporter#784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using  0.40.0-alpha image version and out of nowhere the tag dimension_DBInstanceIdentifier for RDS is not available anymore which makes it impossible for me to distinguish multiple databases.

I tried to update from 0.41.0 to 0.45.0 too and I had same behaviour.

This is current behaviour:

<img width="931" alt="prometheus_rds" src="https://user-images.githubusercontent.com/4260344/216044662-6e466882-3cba-46cf-b6c6-6b926a25e514.PNG">

### Expected Behavior

I"d expect Yace to retrieve this attribute dimension_DBInstanceIdentifier from AWS.

<img width="730" alt="prometheus_rds_01" src="https://user-images.githubusercontent.com/4260344/216043520-4b69fcf9-882f-4580-9940-8ceb40c24bf9.PNG">

**Comment by cristiangreco** [comment]
@danilomattoscamossi thanks for reporting the issue.

>I am using 0.40.0-alpha image version and out of nowhere the tag dimension_DBInstanceIdentifier for RDS is not available anymore 

Do you mean that this happened after an upgrade to 0.40.0 from a previous version? Or did it happen while yace was running?

**Comment by danilomattoscamossi** [comment]
Hello @cristiangreco thank you for replying.

Recently RDS instances has been recreated and hence lost tags, once we added some tags again to those resources the data started to show up again, this lack of tags would explain this behaviour?

As I found this in the github documentation: "Note: Only [tagged resources] are discovered."

Thank you.

**Comment by cristiangreco** [comment]
Yes if you're using discovery jobs you'd need to have tags defined for resources that want to scrape. Yace should also display an info message like "no tagged resources".

**Comment by danilomattoscamossi** [comment]
Thanks for supporting!
