### ISSUE TITLE
[QUESTION] Sudden Increase in "AWS/EC2" Metrics From Terminated Instances

### ISSUE THREAD

**Issue by salessandri** [nerdswords/yet-another-cloudwatch-exporter#904]
## Context

We have been using YACE across all our environments for over two months and YACE has been really stable with the number of metrics being generated pretty correlated with the scaling of our environments.

We have been running the `0.44.0-alpha` release.

## Behavior Change

Around Apr 13th we started seeing an increase in the number of EC2 metrics being reported (CPU Utilization, Disk read/write, etc) without a corresponding increase in our infrastructure base. To make things worse the number just kept (and keeps) increasing.
No configuration changes to our infrastructure nor YACE nor any YACE deployments happened around that date.
This behavior started being observed in all our environments (different accounts and regions) within a short time-frame.

After looking into what was happening, we noticed that before that date we didn't have EC2 metrics with `NaN` but after, the majority of our EC2 metrics are `NaN`. Those metrics are all associated with EC2 instances that have been terminated and not just a few minutes ago but several days before.

## Consequences

The increase in the number of metrics and its steadily increase has been triggering OOM from YACE and it keeps getting harder to maintain it alive.

Also our monitoring infrastructure is suffering due to the increase in metric volume that needs to be ingested and they are useless metrics as those are from terminated instances.

We tried updating YACE to the latest version (`v0.50.0`) but the output remains the same.

## Open Questions

1. Has anyone else been noticing this behavior and more precisely, the _change_ in behavior? 
2. Is it possible to not expose metrics whose value would be `NaN`? I see the option to make them 0 but not to just not export them.
3. There is the `RecentlyActive` argument to the `list-metrics` API call. Has that been explored to use?
4. Has anyone else have to deal with a similar situation? How have you approached it?

### Potentially Related Items

1. [Issue #732](https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/732): Potentially seeing something similar, although having the state in the info metric would not fit the bill for our needs.

**Comment by salessandri** [comment]
Just saw [this PR](https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/903) was open today, related to point 3

**Comment by PerGon** [comment]
Yes, we have been hit by the same.

Regarding your points:
1 - Yes, we saw exactly the same.

3 - As you noted, see PR. It really helped us - still early to tell if it solves a lot, but it seems to help a lot.
4 - Yeah 😄 we are running the code in the PR #903 and it helps.

This seems to be a change done on the AWS side. I actually don't think it was a change in cloudwatch, but yes a change in the [Resource Group Tagging API - Get Resources](https://docs.aws.amazon.com/cli/latest/reference/resourcegroupstaggingapi/get-resources.html). YACE discovers instances tags via this API (it's how we get the `aws_ec2_info` metric) - I suspect that YACE is adding NaN for all metrics of instances that come in the resource tagging api and are not found in the cloudwatch api.
I'm in contact with our AWS TAM to see if I can find more

**Comment by PerGon** [comment]
It seems that AWS has fixed something on their side. Since yesterday around 16:30 CEST, the number of instances fetched from `aws resourcegroupstaggingapi get-resources` started do decrease significantly. Still going down now.

This is the number of `aws_ec2_info` (which uses the `resourcegroupstaggingapi`):

![image](https://user-images.githubusercontent.com/725020/233291631-5e86c141-b654-4e59-8ed0-6fab406e4d09.png)

**Comment by salessandri** [comment]
Hey. Yes, we noticed the same thing. And with that our metric explosion and OOM disappeared. I still think your PR is worth it. I started working on adding a `dropNil` option similar to `nilToZero` that would just drop the metric instead of expose it with a `NaN` value.

In any case, I'm closing this issue.
