### ISSUE TITLE
[BUG] aws_alb_consumed_lcus_average return Nan

### ISSUE THREAD

**Issue by ekfo33** [nerdswords/yet-another-cloudwatch-exporter#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.50.0

### Config file

apiVersion: v1alpha1
sts-region: ap-northeast-2
discovery: 
  exportedTagsOnMetrics:
    alb:
      - Name  
  jobs:
  - type: alb
    regions:
      - ap-northeast-2
    period: 60
    length: 300
    metrics:
      - name: HealthyHostCount
        statistics:
        - Minimum
        nilToZero: true
      - name: UnHealthyHostCount
        statistics:
        - Maximum
        nilToZero: true
      - name: RequestCount
        statistics:
        - Sum
        nilToZero: true
      - name: HTTPCode_ELB_5XX_Count
        statistics:
        - Sum
        nilToZero: true
      - name: HTTPCode_ELB_3XX_Count
        statistics:
        - Sum
        nilToZero: true
      - name: HTTPCode_ELB_4XX_Count
        statistics:
        - Sum
        nilToZero: true
      - name: ActiveConnectionCount
        statistics:
        - Sum
        nilToZero: true
      - name: ClientTLSNegotiationErrorCount
        statistics:
        - Sum
        nilToZero: true
      - name: HTTP_Fixed_Response_Count
        statistics:
        - Sum
        nilToZero: true
      - name: HTTP_Redirect_Count
        statistics:
        - Sum
        nilToZero: true
      - name: HTTP_Redirect_Url_Limit_Exceeded_Count
        statistics:
        - Sum
        nilToZero: true
      - name: IPv6ProcessedBytes
        statistics:
        - Sum
        nilToZero: true
      - name: IPv6RequestCount
        statistics:
        - Sum
        nilToZero: true
      - name: NewConnectionCount
        statistics:
        - Sum
        nilToZero: true
      - name: RejectedConnectionCount
        statistics:
        - Sum
        nilToZero: true
      - name: RuleEvaluations
        statistics:
        - Sum
        nilToZero: true
      - name: ProcessedBytes
        statistics:
        - Average
        nilToZero: true
      - name: TargetResponseTime
        statistics:
        - Average
        nilToZero: true
      - name: TargetConnectionErrorCount
        statistics:
        - Average
        nilToZero: true
      - name: HTTPCode_Target_5XX_Count
        statistics:
        - Sum
        nilToZero: true
      - name: HTTPCode_Target_4XX_Count
        statistics:
        - Sum
        nilToZero: true
      - name: HTTPCode_Target_3XX_Count
        statistics:
        - Sum
        nilToZero: true
      - name: HTTPCode_Target_2XX_Count
        statistics:
        - Sum
        nilToZero: true
      - name: TargetConnectionErrorCount
        statistics:
        - Average
        nilToZero: true
      - name: TargetTLSNegotiationErrorCount
        statistics:
        - Sum
        nilToZero: true
      - name: ClientTLSNegotiationErrorCount
        statistics:
        - Average
        nilToZero: true
      - name: ConsumedLCUs
        statistics:
        - Average
        nilToZero: true

### Current Behavior

aws_alb_consumed_lcus_average is 0
if nilToZero false, return Nan

### Expected Behavior

aws_alb_consumed_lcus_average is not Nan

### Steps To Reproduce

Only ALB ConsumedLCUs was not collected. Other metrics are success by using upper config

### Anything else?

None

**Comment by cristiangreco** [comment]
Hi @ekfo33, could you please run the exporter with `-debug` and paste AWS response content here? (just clean up auth headers please)

**Comment by cristiangreco** [comment]
@ekfo33 I've tested this locally and seems to work correctly. You might need to set a larger period for ConsumedLCUs, as LCU dimensions are averaged over an hour.
