### ISSUE TITLE
[BUG] Failed to get ApiGateway metrics

### ISSUE THREAD

**Issue by gavin-jeong** [nerdswords/yet-another-cloudwatch-exporter#930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.51.0

### Config file

    apiVersion: v1alpha1
    discovery:
      jobs:
      - type: AWS/ApiGateway
        regions:
          - ap-northeast-2
        period: 300
        length: 300
        metrics:
          - name: Count
            statistics: [Sum]

### Current Behavior

```
{"account":"***","arn":"","error":"expected to discover resources but none were found","job_type":"AWS/ApiGateway","level":"error","msg":"No tagged resources made it through filtering","region":"ap-northeast-2","time":"2023-05-08T19:22:52+09:00"}
```

### Expected Behavior

Get the related metrics normally

### Steps To Reproduce

- With the configuration, just run the yace
- And check its log

### Anything else?

Seems all the resources are filtered out from the line 
https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/pkg/clients/tagging/filters.go#L49

If I change it like the below I could see related metrics
```diff
-					searchString := regexp.MustCompile(fmt.Sprintf(".*apis/%s$", *gw.Id))
+					searchString := regexp.MustCompile(fmt.Sprintf(".*apis/%s", *gw.Id))
```

When I checked the related variables, I can see some ARN like the belows
```
arn:aws:apigateway:ap-northeast-2::/restapis/****/stages/****
```

**Comment by wimsymons** [comment]
#586 and #857 are related

**Comment by cristiangreco** [comment]
Closing this now that the above PRs are merged.
