### ISSUE TITLE
[FEATURE] Build for aarch64 architecture

### ISSUE THREAD

**Issue by nuclon** [nerdswords/yet-another-cloudwatch-exporter#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It would be helpful to add aarch64 architecture build.
I believe it is just a modification of the goreleaser config.
Thanks

**Comment by cristiangreco** [comment]
@nuclon can you use the `arm64` release or is there any limitation with that?

**Comment by nuclon** [comment]
@cristiangreco Yes, arm64 works fine.
I have already built arm64 binary, but I thought, that it would be great if you have it for the next releases :)

**Comment by cristiangreco** [comment]
> @cristiangreco Yes, arm64 works fine. I have already built arm64 binary, but I thought, that it would be great if you have it for the next releases :)

Should be already available, e.g. https://github.com/nerdswords/yet-another-cloudwatch-exporter/releases/download/v0.51.0/yet-another-cloudwatch-exporter_0.51.0_Linux_arm64.tar.gz (from [release](https://github.com/nerdswords/yet-another-cloudwatch-exporter/releases) page).

**Comment by cristiangreco** [comment]
@nuclon closing the issue, feel free to re-open if you need any help.
