### ISSUE TITLE
[QUESTION] Release Cadence for YACE 

### ISSUE THREAD

**Issue by mcheung-hbo** [nerdswords/yet-another-cloudwatch-exporter#992]
Hello; Thanks for this awesome project!

I have a quick question: what is the release cadence of YACE? I see that the latest version  ([v0.50.1](https://github.com/nerdswords/yet-another-cloudwatch-exporter/releases/tag/v0.51.0)) is from April 26 and we are seeing issue where this recent feature (`recentlyActiveOnly`) addition can potentially mitigate this:  https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/903. We are just curious where this change will be released?

Context of our issue:
We were seeing AWS CW returning error 413 when YACE asks for metrics, causing data loss, which was possibly due to us having a lot of metrics / dimension combination in a particular custom namespace, and setting the `RecentlyActiveOnly=PT3H` flag may help reducing number of metrics returned from AWS CW.

Thank you!

**Comment by cristiangreco** [comment]
Hi @mcheung-hbo, there's no regular cadence for yace releases at the moment. I think this works fine currently as lots of new features are being worked on and we need some time to get them tested properly.

Anyway, I'm hoping to cut a new release before EOW or early next week.

**Comment by mcheung-hbo** [comment]
Thanks!
